### ISSUE TITLE
application/merge-patch+json is not supported

### ISSUE THREAD

**Issue by daniel-eichinger-bl** [oapi-codegen/nethttp-middleware#16]
I'm unable to use oapi-codegen/nethttp-middleware for `application/merge-patch+json` Content-Types. 
I generated a strict server using: https://github.com/deepmap/oapi-codegen and used your middleware to validate requests.

The request cannot be validated as https://github.com/oapi-codegen/nethttp-middleware/blob/main/oapi_validate.go#L91 returns an error as the https://github.com/getkin/kin-openapi does not provide a decoder for `application/merge-patch+json`.

The maintainers of getkin-openapi made the JSON body decode public (https://github.com/getkin/kin-openapi/pull/896) so it should be possible to register new media types.

**Comment by kogxi** [comment]
Since [openapi3filter.RegisterBodyDecoder](https://pkg.go.dev/github.com/getkin/kin-openapi/openapi3filter#RegisterBodyDecoder) is exported you should be able to workaround this issue by registering the [openapi3filter.JSONBodyDecoder](https://pkg.go.dev/github.com/getkin/kin-openapi/openapi3filter#JSONBodyDecoder) in your code. E.g., `
openapi3filter.RegisterBodyDecoder("application/merge-patch+json“, openapi3filter.JSONBodyDecoder)
`.

**Comment by daniel-eichinger-bl** [comment]
Closing therefore!
